# Generated by Django 5.0.2 on 2024-02-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0002_remove_scontacts_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scontacts',
            new_name='Contact',
        ),
    ]
