# Generated by Django 5.0.2 on 2024-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0003_rename_scontacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=122),
        ),
    ]
