# Generated by Django 5.0.2 on 2024-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
