# Generated by Django 5.0.2 on 2024-02-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0008_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(max_length=200),
        ),
    ]
