# Generated by Django 5.0.2 on 2024-02-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0009_rename_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='apo',
        ),
    ]
