# Generated by Django 5.0.2 on 2024-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0010_rename_appointment_apo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='apo',
        ),
    ]
