# Generated by Django 5.0.2 on 2024-03-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0018_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
