# Generated by Django 5.0.2 on 2024-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0020_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
