# Generated by Django 5.0.2 on 2024-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0022_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(default='Your Company Name', max_length=100)),
                ('address', models.TextField(default='Your Company Address')),
                ('gst_number', models.CharField(default='Your GST Number', max_length=15)),
            ],
        ),
    ]
