# Generated by Django 5.0.2 on 2024-03-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0023_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
