# Generated by Django 5.0.2 on 2024-03-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0025_receipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Invoice',
        ),
    ]
