# Generated by Django 5.0.2 on 2024-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0026_rename_receipt_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
