# Generated by Django 5.0.2 on 2024-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0027_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='INV2024001', max_length=20),
        ),
    ]
