# Generated by Django 5.0.2 on 2024-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0028_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
