# Generated by Django 5.0.2 on 2024-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0031_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
