# Generated by Django 5.0.2 on 2024-04-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massp', '0032_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
